### PR TITLE
upgraded to Swift 5.1

### PR DESCRIPTION
**Pull request by bretsko**

### CODE REVIEW

**Comment by Dids** [comment]
Thanks!

**Comment by bretsko** [comment]
Great! Can you also add a tag for a new version? Thanks

**Comment by Dids** [comment]
Done!

**Comment by bretsko** [comment]
Thanks, looks like some action is also required to bump version in Marketplace, because currently it shows the latest version is still 1.0.0.

**Comment by Dids** [comment]
Should be available now.

Both the syntax and how Actions are handled had changed quite drastically, so I had to bring everything back up to date. Should work again though. :)

**Pull request merged**
